/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AuthCredentials,
  LoginResult,
} from './components/app-auth/app-auth';

export namespace Components {
  interface AppAuth {
    'getCredentials': () => Promise<AuthCredentials>;
    'isLoggedIn': () => Promise<boolean>;
    'logIn': (_username: string, _password: string) => Promise<LoginResult>;
    'logOut': () => Promise<void>;
  }
  interface AppConstruction {}
  interface AppGame {}
  interface AppHome {}
  interface AppInfo {}
  interface AppLogin {
    'showDialog': () => Promise<void>;
  }
  interface AppNavbar {
    'isAuthenticated': boolean;
    'username': string;
  }
  interface AppNews {}
  interface AppProfile {
    'email': string;
    'username': string;
  }
  interface AppRegister {
    'showDialog': () => Promise<void>;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {}
  var HTMLAppAuthElement: {
    prototype: HTMLAppAuthElement;
    new (): HTMLAppAuthElement;
  };

  interface HTMLAppConstructionElement extends Components.AppConstruction, HTMLStencilElement {}
  var HTMLAppConstructionElement: {
    prototype: HTMLAppConstructionElement;
    new (): HTMLAppConstructionElement;
  };

  interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {}
  var HTMLAppGameElement: {
    prototype: HTMLAppGameElement;
    new (): HTMLAppGameElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppInfoElement extends Components.AppInfo, HTMLStencilElement {}
  var HTMLAppInfoElement: {
    prototype: HTMLAppInfoElement;
    new (): HTMLAppInfoElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppNavbarElement extends Components.AppNavbar, HTMLStencilElement {}
  var HTMLAppNavbarElement: {
    prototype: HTMLAppNavbarElement;
    new (): HTMLAppNavbarElement;
  };

  interface HTMLAppNewsElement extends Components.AppNews, HTMLStencilElement {}
  var HTMLAppNewsElement: {
    prototype: HTMLAppNewsElement;
    new (): HTMLAppNewsElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRegisterElement extends Components.AppRegister, HTMLStencilElement {}
  var HTMLAppRegisterElement: {
    prototype: HTMLAppRegisterElement;
    new (): HTMLAppRegisterElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-auth': HTMLAppAuthElement;
    'app-construction': HTMLAppConstructionElement;
    'app-game': HTMLAppGameElement;
    'app-home': HTMLAppHomeElement;
    'app-info': HTMLAppInfoElement;
    'app-login': HTMLAppLoginElement;
    'app-navbar': HTMLAppNavbarElement;
    'app-news': HTMLAppNewsElement;
    'app-profile': HTMLAppProfileElement;
    'app-register': HTMLAppRegisterElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppAuth {}
  interface AppConstruction {}
  interface AppGame {}
  interface AppHome {}
  interface AppInfo {}
  interface AppLogin {}
  interface AppNavbar {
    'isAuthenticated'?: boolean;
    'onLoginModalOpenEvent'?: (event: CustomEvent<any>) => void;
    'onRegisterModalOpenEvent'?: (event: CustomEvent<any>) => void;
    'username'?: string;
  }
  interface AppNews {}
  interface AppProfile {
    'email'?: string;
    'username'?: string;
  }
  interface AppRegister {
    'onRegisterBtnClicked'?: (event: CustomEvent<any>) => void;
  }
  interface AppRoot {}

  interface IntrinsicElements {
    'app-auth': AppAuth;
    'app-construction': AppConstruction;
    'app-game': AppGame;
    'app-home': AppHome;
    'app-info': AppInfo;
    'app-login': AppLogin;
    'app-navbar': AppNavbar;
    'app-news': AppNews;
    'app-profile': AppProfile;
    'app-register': AppRegister;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-auth': LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
      'app-construction': LocalJSX.AppConstruction & JSXBase.HTMLAttributes<HTMLAppConstructionElement>;
      'app-game': LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-info': LocalJSX.AppInfo & JSXBase.HTMLAttributes<HTMLAppInfoElement>;
      'app-login': LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
      'app-navbar': LocalJSX.AppNavbar & JSXBase.HTMLAttributes<HTMLAppNavbarElement>;
      'app-news': LocalJSX.AppNews & JSXBase.HTMLAttributes<HTMLAppNewsElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-register': LocalJSX.AppRegister & JSXBase.HTMLAttributes<HTMLAppRegisterElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


